#common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: OWEzZjBjMjFhOGNkYjY4NGNhZmNmMDcwNGJkNmY0YmEwNzM4YjQ2MzRhMDFlMmUxMGNlYTI2YTdiMWUzYWU1ZGIzZmNmYWIzMWUyMjNjMjkzZTYyZjkwYzY3OTc3ZTUyYjQwZA==
# management:
#   metrics:
#     export:
#       prometheus:
#         enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
